export interface TPmdicExcelRow {
  id: number;
  parcel_no: string;
  pmidc_id: string;
  old_id: string;
  plot_map_id: string;
  property_type: string;
  owner_name: string;
  father_husband_name: string;
  mobile_no: string;
  email: string;
  house_no: string;
  building_name: string;
  locality_name: string;
  road_name: string;
  pin_code: string;
  property_address: string;
  property_use: string;
  occupancy: string;
  construction_type: string;
  construction_year: number | null;
  building_age: number | null;
  plot_area_sqft: number | null;
  builtup_area_sqft: number | null;
  photograph: string | null;
  floor_count: number | null;
  floor_1st_area: number | null;
  floor_1st_use: string | null;
  floor_2nd_area: number | null;
  floor_2nd_use: string | null;
  floor_3rd_area: number | null;
  floor_3rd_use: string | null;
  floor_4th_area: number | null;
  floor_4th_use: string | null;
  floor_5th_area: number | null;
  floor_5th_use: string | null;
  property_tax_id: string | null;
  water_connection_no: string | null;
  sewer_connection_no: string | null;
  electric_connection_no: string | null;
  disposal_id: string | null;
  apartment_building_name: string | null;
  total_no_of_properties: number | null;
  total_builtup_area_sqft: number | null;
  total_no_of_floors: number | null;
  total_open_space_area_sqft: number | null;
  total_res_non_res_holdings: number | null;
  water_source: string | null;
  firm_shop_name: string | null;
  licence_status: string | null;
  firm_owner_address: string | null;
  firm_area_sqft: number | null;
  business_name: string | null;
  remarks: string | null;
}
